const buttonDiv = () => document.getElementById("button-control")
const buttonSignLog = () => document.getElementById("button-signLog")
const buttonEmail = () => document.getElementById("button-signEmail")
const buttonPassword = () => document.getElementById("button-password")
const buttonShowDoctors = () => document.getElementById("button-showDoctors")
const buttonShowReviews = () => document.getElementById("button-showReviews")
const ulDiv = () => document.getElementById("list")
const ul = () => document.getElementById("doctors-list")
const userForm = () => document.getElementById("user-form")
const usersName = () => document.getElementById("users-name")
const doctorsName = () => document.getElementById("doctors-name")
const reviewsForm = () => document.getElementById("reviews-form")
const doctorRating = () => document.getElementById("doctor-rating")
const doctorComments = () => document.getElementById("doctor-comments")
const doctorOfficeRating= () => document.getElementById("office-rating")
const doctorOfficeComments = () => document.getElementById("office-comments")
const doctorId = () => document.getElementById("doctor-id")
const userId = () => document.getElementById("user-id")
