const buttonDiv = () => document.getElementById("button-control")
const buttonShow = () => document.getElementById("button-show")
const buttonNew = () => document.getElementById("button-new")
const ulDiv = () => document.getElementById("list")
const ul = () => document.getElementById("doctors-list")
const doctorsName = () => document.getElementById("doctors-name")
const reviewsForm = () => document.getElementById("reviews-form")
const doctorRating = () => document.getElementById("doctor-rating")
const doctorComments = () => document.getElementById("doctor-comments")
const doctorOfficeRating= () => document.getElementById("office-rating")
const doctorOfficeComments = () => document.getElementById("office-comments")
const doctorId = () => document.getElementById("doctor-id")
const userId = () => document.getElementById("user-id")